version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: abhishek
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: JDBCSpring
    ports:
      - 5433:5432

